name: flutterapp3
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  simple_slider: ^0.0.2
  carousel_slider: ^2.3.1
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3

dev_dependencies:

  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - images/th68DZFGXU.jpg
    - images/thB5GFK80A.jpg
    - images/thVCY7XQGJ.jpg
